name: Java CI with Gradle

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -x test


  deploy_to_render:
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'

    steps:
      - name: Trigger Render Deploy
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK }}"